name: frontend

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: frontend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: aws s3 sync . s3://kiyoshi-udemy/ --exact-timestamp --region ap-northeast-1